# Generated by Django 5.0 on 2024-02-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='title',
            new_name='name',
        ),
    ]
